"""Re-export shim — logic lives in utils/report/contextual_models.py."""

from social_research_probe.utils.report.contextual_models import (
    _baseline_action,
    _parse_numeric,
    _purpose_focus,
    explain_bayesian,
    explain_bootstrap,
    explain_correlation,
    explain_descriptive,
    explain_huber,
    explain_kaplan_meier,
    explain_kmeans,
    explain_multi_regression,
    explain_naive_bayes,
    explain_outliers,
    explain_pca,
    explain_polynomial,
    explain_regression,
    explain_spearman,
    explain_spread,
    explain_tests,
    topic_action_hint,
)

__all__ = [
    "_baseline_action",
    "_parse_numeric",
    "_purpose_focus",
    "explain_bayesian",
    "explain_bootstrap",
    "explain_correlation",
    "explain_descriptive",
    "explain_huber",
    "explain_kaplan_meier",
    "explain_kmeans",
    "explain_multi_regression",
    "explain_naive_bayes",
    "explain_outliers",
    "explain_pca",
    "explain_polynomial",
    "explain_regression",
    "explain_spearman",
    "explain_spread",
    "explain_tests",
    "topic_action_hint",
]
